name: Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::826997462736:role/GitHubTerraformRole
          aws-region: us-east-1

      - run: aws sts get-caller-identity

      - run: terraform init

      - run: terraform plan

      - run: terraform apply -auto-approve
